backend:
  name: git-gateway
  branch: main
media_folder: "_site/img"
public_folder: "/img"
collections:

  # Home
  - label: "Home"
    name: "home"
    folder: "content/home"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }

  # About
  - label: "About"
    name: "about"
    folder: "content/about"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
  
  # Work
  - label: "Work"
    name: "work"
    folder: "content/work"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
  
  # Research
  - label: "Research"
    name: "research"
    folder: "content/research"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }

  # Media
  - label: "Media"
    name: "media"
    folder: "content/media"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }

  # News
  - label: "News"
    name: "news"
    folder: "content/blog"
    create: true    
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Contact
  - label: "Contact"
    name: "contact"
    folder: "content/contact"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
