backend:
  name: git-gateway
  branch: main
media_folder: "_site/img"
public_folder: "/img"
collections:

  # Home
  - label: "Home"
    name: "home"
    folder: "content/home"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Permalink", name: "permalink", widget: "string" }

  # About
  - label: "About"
    name: "about"
    folder: "content/about"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Permalink", name: "permalink", widget: "string" }
  
  # Work
  - label: "Work"
    name: "work"
    folder: "content/work"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Permalink", name: "permalink", widget: "string" }
  
  # Research
  - label: "Research"
    name: "research"
    folder: "content/research"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Permalink", name: "permalink", widget: "string" }

  # Media
  - label: "Media"
    name: "media"
    folder: "content/media"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Permalink", name: "permalink", widget: "string" }

  # News
  - label: "News"
    name: "news"
    folder: "content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Permalink", name: "permalink", widget: "string" }

  # Contact
  - label: "Contact"
    name: "contact"
    folder: "content/contact"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }      
      - { label: "Permalink", name: "permalink", widget: "string" }
